### ISSUE TITLE
Form to adjust/add Doma data (financial information, chores)

### ISSUE THREAD

**Issue by onocy** [onocy/doma#38]
application must implement forms for creating and updating data in your application. Your data model
and database must change through the interaction with these forms.

**Comment by mboneil10** [comment]
I'll be doing the chores form.

**Comment by mboneil10** [comment]
We still need to make forms for finances and events. Unless we're going to bypass that @onocy? I'm just confused.

**Comment by mboneil10** [comment]
And we have yet to reduce the code bulk from it
