### ISSUE TITLE
General Reminder Form

### ISSUE THREAD

**Issue by mboneil10** [onocy/doma#57]

**Comment by mboneil10** [comment]
I don't think events, chores, or transactions have enough overlap between them to benefit from being in a generic reminder form. 

So, I've come up with the following idea. When a user clicks the plus button on the reminders page, a modal will pop up that says: 

```
create a new... 
   chore 
   event 
   finance
```

Clicking on `chore`, `event`, or `finance` will lead them to the corresponding create page. 
Have yet to know what to do with the cases for edit/delete. Worse comes to worst we keep the reminders page as is, sorted by events, finances, and lastly chores.

**Comment by mboneil10** [comment]
Taking me forever to figure out how to make this modal work. Promise I'm actually working on this. If I don't get the modal to work, I'll make the plus go to a separate page that has the above. :/

**Comment by L4r1k** [comment]
This sounds more like a 'to-do list' than a dynamic reminder page. The overlap between events, chore and transactions is that they all have dates which can be used to pull them into 'reminders'
