### ISSUE TITLE
User Association

### ISSUE THREAD

**Issue by mboneil10** [onocy/doma#59]
Register multiple users and have the ability to assign them to a house. For the sake of the Finance Page (dividing cost among the house).

**Comment by mboneil10** [comment]
Related to #58

**Comment by TheMartyred** [comment]
multiple users can already be associated with a home, it's simply a matter of determining what users are associated with the home that is associated with the transaction. I did, however, associate the transaction model with a home as well as the chores and reminder lists. (and fixed one other bug with money amounts) would you like me to close this task or is there anything additional that needs to be completed first?
